version: "3.2"
services:
  database:
    container_name: superindo-database
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - superindo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - superindo
  migrate:
    image: migrate/migrate
    env_file:
      - .env
    networks:
      - superindo
    volumes:
      - ./db/migration:/migration
    depends_on:
      database:
        condition: service_healthy
        restart: true
    command:
      [
        "-path",
        "./migration",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@superindo-database:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL}",
        "up",
      ]
  app:
    networks:
      - superindo
    ports:
      - "8080:8080"
    build: .
    container_name: superindoapp
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
networks:
  superindo:
    driver: bridge
volumes:
  database-data:
