BEGIN
;

CREATE TABLE IF NOT EXISTS "types" (
    "name" VARCHAR PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ NULL
);

CREATE TRIGGER "log_type_update" BEFORE
UPDATE
    ON "types" FOR EACH ROW EXECUTE PROCEDURE log_update_master();

COMMIT;