// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/elangreza14/lion-superindo/cmd/server/config"
	"github.com/elangreza14/lion-superindo/internal/handler"
	"github.com/elangreza14/lion-superindo/internal/postgresql"
	"github.com/elangreza14/lion-superindo/internal/redis"
	"github.com/elangreza14/lion-superindo/internal/service"
	"github.com/google/wire"
	redis2 "github.com/redis/go-redis/v9"
	"net/http"
)

import (
	_ "github.com/elangreza14/lion-superindo/docs"
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeProductHandler(cfg *config.Config) (*ProductHandlerDeps, error) {
	db, err := setupDB(cfg)
	if err != nil {
		return nil, err
	}
	postgresRepo := postgresql.NewRepo(db)
	client, err := setupCache(cfg)
	if err != nil {
		return nil, err
	}
	redisRepo := redis.NewRepo(client)
	productService := service.NewProductService(postgresRepo, redisRepo)
	productHandler := handler.NewProductHandler(productService)
	serveMux := handler.NewRoutes(productHandler)
	productHandlerDeps := &ProductHandlerDeps{
		Mux:         serveMux,
		DB:          db,
		RedisClient: client,
	}
	return productHandlerDeps, nil
}

// wire.go:

type ProductHandlerDeps struct {
	Mux         *http.ServeMux
	DB          *sql.DB
	RedisClient *redis2.Client
}

var productSet = wire.NewSet(
	setupDB,
	setupCache, postgresql.NewRepo, wire.Bind(new(service.DbRepo), new(*postgresql.PostgresRepo)), redis.NewRepo, wire.Bind(new(service.CacheRepo), new(*redis.RedisRepo)), service.NewProductService, wire.Bind(new(handler.ProductService), new(*service.ProductService)), handler.NewProductHandler, handler.NewRoutes,
)

func setupDB(cfg *config.Config) (*sql.DB, error) {
	connString := fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=%s",
		cfg.POSTGRES_USER,
		cfg.POSTGRES_PASSWORD,
		cfg.POSTGRES_HOSTNAME,
		cfg.POSTGRES_PORT,
		cfg.POSTGRES_DB,
		cfg.POSTGRES_SSL,
	)

	db, err := sql.Open("postgres", connString)
	if err != nil {
		return nil, err
	}

	err = db.Ping()
	if err != nil {
		return nil, err
	}

	return db, nil
}

func setupCache(cfg *config.Config) (*redis2.Client, error) {
	redisClient := redis2.NewClient(&redis2.Options{
		Addr: fmt.Sprintf("%s:%s", cfg.REDIS_HOSTNAME, cfg.REDIS_PORT),
	})

	err := redisClient.Ping(context.Background()).Err()
	if err != nil {
		return nil, err
	}

	return redisClient, nil
}
